name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  intl: ^0.20.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^16.2.0

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.11

  # Health
  health: ^13.1.3

  # Notifications
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
